// MyLeetCode.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "../Questions/TwoSum/TwoSum.cpp"
#include "../Questions/MedianofTwoSortedArrays/MedianofTwoSortedArrays.cpp"
#include "../Questions/LongestSubstring/LongestSubstring.cpp"
#include "../Questions/AddTwoNums/AddTwoNums.cpp"
#include "../Questions/LongestPalindromicSubstring/LongestPalindromicSubstring.cpp"
#include "../Questions/ZigZagConversion/ZigZagConversion.cpp"
#include "../Questions/ReverseInteger/ReverseInteger.cpp"
#include "../Questions/StringtoInteger/StringtoInteger.cpp"
#include "../Questions/PalindromeNumber/PalindromeNumber.cpp"
#include "../Questions/RegularExpressionMatching/RegularExpressionMatching.cpp"
#include "../Questions/ContainerWithMostWater/ContainerWithMostWater.cpp"
#include "../Questions/IntegertoRoman/IntegertoRoman.cpp"
#include "../Questions/RomantoInteger/RomantoInteger.cpp"
#include "../Questions/LongestCommonPrefix/LongestCommonPrefix.cpp"
#include "../Questions/3Sum/3Sum.cpp"
#include "../Questions/3SumClosest/3SumClosest.cpp"
#include "../Questions/LetterCombinationsofaPhoneNumber/LetterCombinationsofaPhoneNumber.cpp"
#include "../Questions/4Sum/4Sum.cpp"
#include "../Questions/RemoveNthNodeFromEndofList/RemoveNthNodeFromEndofList.cpp"
#include "../Questions/ValidParentheses/ValidParentheses.cpp"
#include "../Questions/MergeTwoSortedLists/MergeTwoSortedLists.cpp"
#include "../Questions/GenerateParentheses/GenerateParentheses.cpp"
#include "../Questions/MergekSortedLists/MergekSortedLists.cpp"
#include "../Questions/SwapNodesinPairs/SwapNodesinPairs.cpp"
#include "../Questions/ReverseNodesink-Group/ReverseNodesink-Group.cpp"
#include "../Questions/RemoveDuplicatesfromSortedArray/RemoveDuplicatesfromSortedArray.cpp"
#include "../Questions/ImplementstrStr()/ImplementstrStr.cpp"
#include "../Questions/DivideTwoIntegers/DivideTwoIntegers.cpp"
#include "../Questions/SubstringwithConcatenationofAllWords/SubstringwithConcatenationofAllWords.cpp"
#include "../Questions/NextPermutation/NextPermutation.cpp"
#include "../Questions/LongestValidParentheses/LongestValidParentheses.cpp"
#include "../Questions/SearchinRotatedSortedArray/SearchinRotatedSortedArray.cpp"
#include "../Questions/SearchforaRange/SearchforaRange.cpp"
#include "../Questions/SearchInsertPosition/SearchInsertPosition.cpp"
#include "../Questions/ValidSudoku/ValidSudoku.cpp"
#include "../Questions/SudokuSolver/SudokuSolver.cpp"
#include "../Questions/CountandSay/CountandSay.cpp"
#include "../Questions/CombinationSum/CombinationSum.cpp"
#include "../Questions/CombinationSumII/CombinationSumII.cpp"
#include "../Questions/FirstMissingPositive/FirstMissingPositive.cpp"
#include "../Questions/TrappingRainWater/TrappingRainWater.cpp"
#include "../Questions/MultiplyStrings/MultiplyStrings.cpp"
#include "../Questions/WildcardMatching/WildcardMatching.cpp"
#include "../Questions/JumpGame/JumpGame.cpp"
#include "../Questions/JumpGameII/JumpGameII.cpp"
#include "../Questions/Permutations/Permutations.cpp"
#include "../Questions/PermutationsII/PermutationsII.cpp"
#include "../Questions/RotateImage/RotateImage.cpp"
#include "../Questions/Pow(x, n)/Pow(x, n).cpp"
#include "../Questions/N-Queens/N-Queens.cpp"
#include "../Questions/N-Queens II/N-Queens II.cpp"
#include "../Questions/MaximumSubarray/MaximumSubarray.cpp"
#include "../Questions/SpiralMatrix/SpiralMatrix.cpp"
#include "../Questions/MergeIntervals/MergeIntervals.cpp"
#include "../Questions/InsertInterval/InsertInterval.cpp"

int _tmain(int argc, _TCHAR* argv[])
{
	InsertInterval obj;
	
	return 0;
}

